apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-node-template-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-node-server
    spec:
      containers:
      - name: k8s-node-server
        image: gokulpersonal.azurecr.io/k8s-node-template:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
