apiVersion: v1
kind: Service
metadata:
  name: k8s-node-server-service
  labels:
    app: k8s-node-server-service
spec:
  selector:
    app: k8s-node-server
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  type: NodePort
